/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ConfirmarExclusaoRouteImport } from './routes/confirmar-exclusao'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthConfirmarRouteImport } from './routes/auth.confirmar'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiVozTranscreverRouteImport } from './routes/api/voz/transcrever'
import { Route as ApiVozFalarRouteImport } from './routes/api/voz/falar'
import { Route as ApiPublicDemoChatRouteImport } from './routes/api/public/demo-chat'
import { Route as ApiPublicAuthCheckRouteImport } from './routes/api/public/auth-check'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as AuthenticatedAppContaRouteImport } from './routes/_authenticated/app.conta'
import { Route as AuthenticatedAppAssinaturaRouteImport } from './routes/_authenticated/app.assinatura'
import { Route as AuthenticatedAppAjudaRouteImport } from './routes/_authenticated/app.ajuda'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppCondominiosIndexRouteImport } from './routes/_authenticated/app.condominios.index'
import { Route as AuthenticatedAppAjudaIndexRouteImport } from './routes/_authenticated/app.ajuda.index'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicHooksHelpdeskLembretesRouteImport } from './routes/api/public/hooks/helpdesk-lembretes'
import { Route as AuthenticatedAppSuporteTicketIdRouteImport } from './routes/_authenticated/app.suporte.$ticketId'
import { Route as AuthenticatedAppCondominiosIdRouteImport } from './routes/_authenticated/app.condominios.$id'
import { Route as AuthenticatedAppAssinaturaRetornoRouteImport } from './routes/_authenticated/app.assinatura.retorno'
import { Route as AuthenticatedAppAjudaFaqRouteImport } from './routes/_authenticated/app.ajuda.faq'
import { Route as AuthenticatedAppAjudaDicasIaRouteImport } from './routes/_authenticated/app.ajuda.dicas-ia'
import { Route as AuthenticatedAppAjudaSecaoRouteImport } from './routes/_authenticated/app.ajuda.$secao'
import { Route as AuthenticatedAppAdminUsoRouteImport } from './routes/_authenticated/app.admin.uso'
import { Route as AuthenticatedAppAdminTreinamentoRouteImport } from './routes/_authenticated/app.admin.treinamento'
import { Route as AuthenticatedAppAdminOrientacoesRouteImport } from './routes/_authenticated/app.admin.orientacoes'
import { Route as AuthenticatedAppAdminImoveisRouteImport } from './routes/_authenticated/app.admin.imoveis'
import { Route as AuthenticatedAppAdminFinanceiroRouteImport } from './routes/_authenticated/app.admin.financeiro'
import { Route as AuthenticatedAppAdminCondominiosRouteImport } from './routes/_authenticated/app.admin.condominios'
import { Route as AuthenticatedAppAdminCidadesNovasRouteImport } from './routes/_authenticated/app.admin.cidades-novas'
import { Route as AuthenticatedAppAdminBlogRouteImport } from './routes/_authenticated/app.admin.blog'
import { Route as AuthenticatedAppAdminAuditoriaRouteImport } from './routes/_authenticated/app.admin.auditoria'
import { Route as AuthenticatedAppAdminUsuariosIndexRouteImport } from './routes/_authenticated/app.admin.usuarios.index'
import { Route as AuthenticatedAppAdminImoveisIndexRouteImport } from './routes/_authenticated/app.admin.imoveis.index'
import { Route as AuthenticatedAppAdminHelpdeskIndexRouteImport } from './routes/_authenticated/app.admin.helpdesk.index'
import { Route as AuthenticatedAppAjudaPerfilPerfilRouteImport } from './routes/_authenticated/app.ajuda.perfil.$perfil'
import { Route as AuthenticatedAppAdminUsuariosUserIdRouteImport } from './routes/_authenticated/app.admin.usuarios.$userId'
import { Route as AuthenticatedAppAdminImoveisImportarRouteImport } from './routes/_authenticated/app.admin.imoveis.importar'
import { Route as AuthenticatedAppAdminHelpdeskTicketIdRouteImport } from './routes/_authenticated/app.admin.helpdesk.$ticketId'
import { Route as AuthenticatedAppAdminImoveisUnidadesIndexRouteImport } from './routes/_authenticated/app.admin.imoveis.unidades.index'
import { Route as AuthenticatedAppAdminImoveisProprietariosIndexRouteImport } from './routes/_authenticated/app.admin.imoveis.proprietarios.index'
import { Route as AuthenticatedAppAdminImoveisLocacaoIndexRouteImport } from './routes/_authenticated/app.admin.imoveis.locacao.index'
import { Route as AuthenticatedAppAdminImoveisHonorariosIndexRouteImport } from './routes/_authenticated/app.admin.imoveis.honorarios.index'
import { Route as AuthenticatedAppAdminImoveisAdministracaoIndexRouteImport } from './routes/_authenticated/app.admin.imoveis.administracao.index'
import { Route as AuthenticatedAppAdminImoveisUnidadesIdRouteImport } from './routes/_authenticated/app.admin.imoveis.unidades.$id'
import { Route as AuthenticatedAppAdminImoveisProprietariosIdRouteImport } from './routes/_authenticated/app.admin.imoveis.proprietarios.$id'
import { Route as AuthenticatedAppAdminImoveisAdministracaoIdRouteImport } from './routes/_authenticated/app.admin.imoveis.administracao.$id'
import { Route as AuthenticatedAppAdminImoveisLocacaoIdIndexRouteImport } from './routes/_authenticated/app.admin.imoveis.locacao.$id.index'
import { Route as AuthenticatedAppAdminImoveisLocacaoIdEditarRouteImport } from './routes/_authenticated/app.admin.imoveis.locacao.$id.editar'
import { Route as AuthenticatedAppAdminImoveisLocacaoIdAditivoRouteImport } from './routes/_authenticated/app.admin.imoveis.locacao.$id.aditivo'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarExclusaoRoute = ConfirmarExclusaoRouteImport.update({
  id: '/confirmar-exclusao',
  path: '/confirmar-exclusao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmarRoute = AuthConfirmarRouteImport.update({
  id: '/auth/confirmar',
  path: '/auth/confirmar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVozTranscreverRoute = ApiVozTranscreverRouteImport.update({
  id: '/api/voz/transcrever',
  path: '/api/voz/transcrever',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVozFalarRoute = ApiVozFalarRouteImport.update({
  id: '/api/voz/falar',
  path: '/api/voz/falar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDemoChatRoute = ApiPublicDemoChatRouteImport.update({
  id: '/api/public/demo-chat',
  path: '/api/public/demo-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthCheckRoute = ApiPublicAuthCheckRouteImport.update({
  id: '/api/public/auth-check',
  path: '/api/public/auth-check',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppContaRoute = AuthenticatedAppContaRouteImport.update({
  id: '/app/conta',
  path: '/app/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAssinaturaRoute =
  AuthenticatedAppAssinaturaRouteImport.update({
    id: '/app/assinatura',
    path: '/app/assinatura',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAjudaRoute = AuthenticatedAppAjudaRouteImport.update({
  id: '/app/ajuda',
  path: '/app/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCondominiosIndexRoute =
  AuthenticatedAppCondominiosIndexRouteImport.update({
    id: '/app/condominios/',
    path: '/app/condominios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAjudaIndexRoute =
  AuthenticatedAppAjudaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksHelpdeskLembretesRoute =
  ApiPublicHooksHelpdeskLembretesRouteImport.update({
    id: '/api/public/hooks/helpdesk-lembretes',
    path: '/api/public/hooks/helpdesk-lembretes',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppSuporteTicketIdRoute =
  AuthenticatedAppSuporteTicketIdRouteImport.update({
    id: '/app/suporte/$ticketId',
    path: '/app/suporte/$ticketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCondominiosIdRoute =
  AuthenticatedAppCondominiosIdRouteImport.update({
    id: '/app/condominios/$id',
    path: '/app/condominios/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAssinaturaRetornoRoute =
  AuthenticatedAppAssinaturaRetornoRouteImport.update({
    id: '/retorno',
    path: '/retorno',
    getParentRoute: () => AuthenticatedAppAssinaturaRoute,
  } as any)
const AuthenticatedAppAjudaFaqRoute =
  AuthenticatedAppAjudaFaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAjudaDicasIaRoute =
  AuthenticatedAppAjudaDicasIaRouteImport.update({
    id: '/dicas-ia',
    path: '/dicas-ia',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAjudaSecaoRoute =
  AuthenticatedAppAjudaSecaoRouteImport.update({
    id: '/$secao',
    path: '/$secao',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAdminUsoRoute =
  AuthenticatedAppAdminUsoRouteImport.update({
    id: '/uso',
    path: '/uso',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminTreinamentoRoute =
  AuthenticatedAppAdminTreinamentoRouteImport.update({
    id: '/treinamento',
    path: '/treinamento',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminOrientacoesRoute =
  AuthenticatedAppAdminOrientacoesRouteImport.update({
    id: '/orientacoes',
    path: '/orientacoes',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminImoveisRoute =
  AuthenticatedAppAdminImoveisRouteImport.update({
    id: '/imoveis',
    path: '/imoveis',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminFinanceiroRoute =
  AuthenticatedAppAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminCondominiosRoute =
  AuthenticatedAppAdminCondominiosRouteImport.update({
    id: '/condominios',
    path: '/condominios',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminCidadesNovasRoute =
  AuthenticatedAppAdminCidadesNovasRouteImport.update({
    id: '/cidades-novas',
    path: '/cidades-novas',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminBlogRoute =
  AuthenticatedAppAdminBlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminAuditoriaRoute =
  AuthenticatedAppAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminUsuariosIndexRoute =
  AuthenticatedAppAdminUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminImoveisIndexRoute =
  AuthenticatedAppAdminImoveisIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminHelpdeskIndexRoute =
  AuthenticatedAppAdminHelpdeskIndexRouteImport.update({
    id: '/helpdesk/',
    path: '/helpdesk/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAjudaPerfilPerfilRoute =
  AuthenticatedAppAjudaPerfilPerfilRouteImport.update({
    id: '/perfil/$perfil',
    path: '/perfil/$perfil',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAdminUsuariosUserIdRoute =
  AuthenticatedAppAdminUsuariosUserIdRouteImport.update({
    id: '/usuarios/$userId',
    path: '/usuarios/$userId',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminImoveisImportarRoute =
  AuthenticatedAppAdminImoveisImportarRouteImport.update({
    id: '/importar',
    path: '/importar',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminHelpdeskTicketIdRoute =
  AuthenticatedAppAdminHelpdeskTicketIdRouteImport.update({
    id: '/helpdesk/$ticketId',
    path: '/helpdesk/$ticketId',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminImoveisUnidadesIndexRoute =
  AuthenticatedAppAdminImoveisUnidadesIndexRouteImport.update({
    id: '/unidades/',
    path: '/unidades/',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisProprietariosIndexRoute =
  AuthenticatedAppAdminImoveisProprietariosIndexRouteImport.update({
    id: '/proprietarios/',
    path: '/proprietarios/',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisLocacaoIndexRoute =
  AuthenticatedAppAdminImoveisLocacaoIndexRouteImport.update({
    id: '/locacao/',
    path: '/locacao/',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisHonorariosIndexRoute =
  AuthenticatedAppAdminImoveisHonorariosIndexRouteImport.update({
    id: '/honorarios/',
    path: '/honorarios/',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisAdministracaoIndexRoute =
  AuthenticatedAppAdminImoveisAdministracaoIndexRouteImport.update({
    id: '/administracao/',
    path: '/administracao/',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisUnidadesIdRoute =
  AuthenticatedAppAdminImoveisUnidadesIdRouteImport.update({
    id: '/unidades/$id',
    path: '/unidades/$id',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisProprietariosIdRoute =
  AuthenticatedAppAdminImoveisProprietariosIdRouteImport.update({
    id: '/proprietarios/$id',
    path: '/proprietarios/$id',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisAdministracaoIdRoute =
  AuthenticatedAppAdminImoveisAdministracaoIdRouteImport.update({
    id: '/administracao/$id',
    path: '/administracao/$id',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisLocacaoIdIndexRoute =
  AuthenticatedAppAdminImoveisLocacaoIdIndexRouteImport.update({
    id: '/locacao/$id/',
    path: '/locacao/$id/',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisLocacaoIdEditarRoute =
  AuthenticatedAppAdminImoveisLocacaoIdEditarRouteImport.update({
    id: '/locacao/$id/editar',
    path: '/locacao/$id/editar',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)
const AuthenticatedAppAdminImoveisLocacaoIdAditivoRoute =
  AuthenticatedAppAdminImoveisLocacaoIdAditivoRouteImport.update({
    id: '/locacao/$id/aditivo',
    path: '/locacao/$id/aditivo',
    getParentRoute: () => AuthenticatedAppAdminImoveisRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmar-exclusao': typeof ConfirmarExclusaoRoute
  '/contato': typeof ContatoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/confirmar': typeof AuthConfirmarRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/ajuda': typeof AuthenticatedAppAjudaRouteWithChildren
  '/app/assinatura': typeof AuthenticatedAppAssinaturaRouteWithChildren
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/auth-check': typeof ApiPublicAuthCheckRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/api/voz/falar': typeof ApiVozFalarRoute
  '/api/voz/transcrever': typeof ApiVozTranscreverRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/auditoria': typeof AuthenticatedAppAdminAuditoriaRoute
  '/app/admin/blog': typeof AuthenticatedAppAdminBlogRoute
  '/app/admin/cidades-novas': typeof AuthenticatedAppAdminCidadesNovasRoute
  '/app/admin/condominios': typeof AuthenticatedAppAdminCondominiosRoute
  '/app/admin/financeiro': typeof AuthenticatedAppAdminFinanceiroRoute
  '/app/admin/imoveis': typeof AuthenticatedAppAdminImoveisRouteWithChildren
  '/app/admin/orientacoes': typeof AuthenticatedAppAdminOrientacoesRoute
  '/app/admin/treinamento': typeof AuthenticatedAppAdminTreinamentoRoute
  '/app/admin/uso': typeof AuthenticatedAppAdminUsoRoute
  '/app/ajuda/$secao': typeof AuthenticatedAppAjudaSecaoRoute
  '/app/ajuda/dicas-ia': typeof AuthenticatedAppAjudaDicasIaRoute
  '/app/ajuda/faq': typeof AuthenticatedAppAjudaFaqRoute
  '/app/assinatura/retorno': typeof AuthenticatedAppAssinaturaRetornoRoute
  '/app/condominios/$id': typeof AuthenticatedAppCondominiosIdRoute
  '/app/suporte/$ticketId': typeof AuthenticatedAppSuporteTicketIdRoute
  '/api/public/hooks/helpdesk-lembretes': typeof ApiPublicHooksHelpdeskLembretesRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/ajuda/': typeof AuthenticatedAppAjudaIndexRoute
  '/app/condominios/': typeof AuthenticatedAppCondominiosIndexRoute
  '/app/admin/helpdesk/$ticketId': typeof AuthenticatedAppAdminHelpdeskTicketIdRoute
  '/app/admin/imoveis/importar': typeof AuthenticatedAppAdminImoveisImportarRoute
  '/app/admin/usuarios/$userId': typeof AuthenticatedAppAdminUsuariosUserIdRoute
  '/app/ajuda/perfil/$perfil': typeof AuthenticatedAppAjudaPerfilPerfilRoute
  '/app/admin/helpdesk/': typeof AuthenticatedAppAdminHelpdeskIndexRoute
  '/app/admin/imoveis/': typeof AuthenticatedAppAdminImoveisIndexRoute
  '/app/admin/usuarios/': typeof AuthenticatedAppAdminUsuariosIndexRoute
  '/app/admin/imoveis/administracao/$id': typeof AuthenticatedAppAdminImoveisAdministracaoIdRoute
  '/app/admin/imoveis/proprietarios/$id': typeof AuthenticatedAppAdminImoveisProprietariosIdRoute
  '/app/admin/imoveis/unidades/$id': typeof AuthenticatedAppAdminImoveisUnidadesIdRoute
  '/app/admin/imoveis/administracao/': typeof AuthenticatedAppAdminImoveisAdministracaoIndexRoute
  '/app/admin/imoveis/honorarios/': typeof AuthenticatedAppAdminImoveisHonorariosIndexRoute
  '/app/admin/imoveis/locacao/': typeof AuthenticatedAppAdminImoveisLocacaoIndexRoute
  '/app/admin/imoveis/proprietarios/': typeof AuthenticatedAppAdminImoveisProprietariosIndexRoute
  '/app/admin/imoveis/unidades/': typeof AuthenticatedAppAdminImoveisUnidadesIndexRoute
  '/app/admin/imoveis/locacao/$id/aditivo': typeof AuthenticatedAppAdminImoveisLocacaoIdAditivoRoute
  '/app/admin/imoveis/locacao/$id/editar': typeof AuthenticatedAppAdminImoveisLocacaoIdEditarRoute
  '/app/admin/imoveis/locacao/$id/': typeof AuthenticatedAppAdminImoveisLocacaoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmar-exclusao': typeof ConfirmarExclusaoRoute
  '/contato': typeof ContatoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/confirmar': typeof AuthConfirmarRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/app/assinatura': typeof AuthenticatedAppAssinaturaRouteWithChildren
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/auth-check': typeof ApiPublicAuthCheckRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/api/voz/falar': typeof ApiVozFalarRoute
  '/api/voz/transcrever': typeof ApiVozTranscreverRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/auditoria': typeof AuthenticatedAppAdminAuditoriaRoute
  '/app/admin/blog': typeof AuthenticatedAppAdminBlogRoute
  '/app/admin/cidades-novas': typeof AuthenticatedAppAdminCidadesNovasRoute
  '/app/admin/condominios': typeof AuthenticatedAppAdminCondominiosRoute
  '/app/admin/financeiro': typeof AuthenticatedAppAdminFinanceiroRoute
  '/app/admin/orientacoes': typeof AuthenticatedAppAdminOrientacoesRoute
  '/app/admin/treinamento': typeof AuthenticatedAppAdminTreinamentoRoute
  '/app/admin/uso': typeof AuthenticatedAppAdminUsoRoute
  '/app/ajuda/$secao': typeof AuthenticatedAppAjudaSecaoRoute
  '/app/ajuda/dicas-ia': typeof AuthenticatedAppAjudaDicasIaRoute
  '/app/ajuda/faq': typeof AuthenticatedAppAjudaFaqRoute
  '/app/assinatura/retorno': typeof AuthenticatedAppAssinaturaRetornoRoute
  '/app/condominios/$id': typeof AuthenticatedAppCondominiosIdRoute
  '/app/suporte/$ticketId': typeof AuthenticatedAppSuporteTicketIdRoute
  '/api/public/hooks/helpdesk-lembretes': typeof ApiPublicHooksHelpdeskLembretesRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/ajuda': typeof AuthenticatedAppAjudaIndexRoute
  '/app/condominios': typeof AuthenticatedAppCondominiosIndexRoute
  '/app/admin/helpdesk/$ticketId': typeof AuthenticatedAppAdminHelpdeskTicketIdRoute
  '/app/admin/imoveis/importar': typeof AuthenticatedAppAdminImoveisImportarRoute
  '/app/admin/usuarios/$userId': typeof AuthenticatedAppAdminUsuariosUserIdRoute
  '/app/ajuda/perfil/$perfil': typeof AuthenticatedAppAjudaPerfilPerfilRoute
  '/app/admin/helpdesk': typeof AuthenticatedAppAdminHelpdeskIndexRoute
  '/app/admin/imoveis': typeof AuthenticatedAppAdminImoveisIndexRoute
  '/app/admin/usuarios': typeof AuthenticatedAppAdminUsuariosIndexRoute
  '/app/admin/imoveis/administracao/$id': typeof AuthenticatedAppAdminImoveisAdministracaoIdRoute
  '/app/admin/imoveis/proprietarios/$id': typeof AuthenticatedAppAdminImoveisProprietariosIdRoute
  '/app/admin/imoveis/unidades/$id': typeof AuthenticatedAppAdminImoveisUnidadesIdRoute
  '/app/admin/imoveis/administracao': typeof AuthenticatedAppAdminImoveisAdministracaoIndexRoute
  '/app/admin/imoveis/honorarios': typeof AuthenticatedAppAdminImoveisHonorariosIndexRoute
  '/app/admin/imoveis/locacao': typeof AuthenticatedAppAdminImoveisLocacaoIndexRoute
  '/app/admin/imoveis/proprietarios': typeof AuthenticatedAppAdminImoveisProprietariosIndexRoute
  '/app/admin/imoveis/unidades': typeof AuthenticatedAppAdminImoveisUnidadesIndexRoute
  '/app/admin/imoveis/locacao/$id/aditivo': typeof AuthenticatedAppAdminImoveisLocacaoIdAditivoRoute
  '/app/admin/imoveis/locacao/$id/editar': typeof AuthenticatedAppAdminImoveisLocacaoIdEditarRoute
  '/app/admin/imoveis/locacao/$id': typeof AuthenticatedAppAdminImoveisLocacaoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/confirmar-exclusao': typeof ConfirmarExclusaoRoute
  '/contato': typeof ContatoRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/termos': typeof TermosRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/confirmar': typeof AuthConfirmarRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/ajuda': typeof AuthenticatedAppAjudaRouteWithChildren
  '/_authenticated/app/assinatura': typeof AuthenticatedAppAssinaturaRouteWithChildren
  '/_authenticated/app/conta': typeof AuthenticatedAppContaRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/auth-check': typeof ApiPublicAuthCheckRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/api/voz/falar': typeof ApiVozFalarRoute
  '/api/voz/transcrever': typeof ApiVozTranscreverRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/auditoria': typeof AuthenticatedAppAdminAuditoriaRoute
  '/_authenticated/app/admin/blog': typeof AuthenticatedAppAdminBlogRoute
  '/_authenticated/app/admin/cidades-novas': typeof AuthenticatedAppAdminCidadesNovasRoute
  '/_authenticated/app/admin/condominios': typeof AuthenticatedAppAdminCondominiosRoute
  '/_authenticated/app/admin/financeiro': typeof AuthenticatedAppAdminFinanceiroRoute
  '/_authenticated/app/admin/imoveis': typeof AuthenticatedAppAdminImoveisRouteWithChildren
  '/_authenticated/app/admin/orientacoes': typeof AuthenticatedAppAdminOrientacoesRoute
  '/_authenticated/app/admin/treinamento': typeof AuthenticatedAppAdminTreinamentoRoute
  '/_authenticated/app/admin/uso': typeof AuthenticatedAppAdminUsoRoute
  '/_authenticated/app/ajuda/$secao': typeof AuthenticatedAppAjudaSecaoRoute
  '/_authenticated/app/ajuda/dicas-ia': typeof AuthenticatedAppAjudaDicasIaRoute
  '/_authenticated/app/ajuda/faq': typeof AuthenticatedAppAjudaFaqRoute
  '/_authenticated/app/assinatura/retorno': typeof AuthenticatedAppAssinaturaRetornoRoute
  '/_authenticated/app/condominios/$id': typeof AuthenticatedAppCondominiosIdRoute
  '/_authenticated/app/suporte/$ticketId': typeof AuthenticatedAppSuporteTicketIdRoute
  '/api/public/hooks/helpdesk-lembretes': typeof ApiPublicHooksHelpdeskLembretesRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/ajuda/': typeof AuthenticatedAppAjudaIndexRoute
  '/_authenticated/app/condominios/': typeof AuthenticatedAppCondominiosIndexRoute
  '/_authenticated/app/admin/helpdesk/$ticketId': typeof AuthenticatedAppAdminHelpdeskTicketIdRoute
  '/_authenticated/app/admin/imoveis/importar': typeof AuthenticatedAppAdminImoveisImportarRoute
  '/_authenticated/app/admin/usuarios/$userId': typeof AuthenticatedAppAdminUsuariosUserIdRoute
  '/_authenticated/app/ajuda/perfil/$perfil': typeof AuthenticatedAppAjudaPerfilPerfilRoute
  '/_authenticated/app/admin/helpdesk/': typeof AuthenticatedAppAdminHelpdeskIndexRoute
  '/_authenticated/app/admin/imoveis/': typeof AuthenticatedAppAdminImoveisIndexRoute
  '/_authenticated/app/admin/usuarios/': typeof AuthenticatedAppAdminUsuariosIndexRoute
  '/_authenticated/app/admin/imoveis/administracao/$id': typeof AuthenticatedAppAdminImoveisAdministracaoIdRoute
  '/_authenticated/app/admin/imoveis/proprietarios/$id': typeof AuthenticatedAppAdminImoveisProprietariosIdRoute
  '/_authenticated/app/admin/imoveis/unidades/$id': typeof AuthenticatedAppAdminImoveisUnidadesIdRoute
  '/_authenticated/app/admin/imoveis/administracao/': typeof AuthenticatedAppAdminImoveisAdministracaoIndexRoute
  '/_authenticated/app/admin/imoveis/honorarios/': typeof AuthenticatedAppAdminImoveisHonorariosIndexRoute
  '/_authenticated/app/admin/imoveis/locacao/': typeof AuthenticatedAppAdminImoveisLocacaoIndexRoute
  '/_authenticated/app/admin/imoveis/proprietarios/': typeof AuthenticatedAppAdminImoveisProprietariosIndexRoute
  '/_authenticated/app/admin/imoveis/unidades/': typeof AuthenticatedAppAdminImoveisUnidadesIndexRoute
  '/_authenticated/app/admin/imoveis/locacao/$id/aditivo': typeof AuthenticatedAppAdminImoveisLocacaoIdAditivoRoute
  '/_authenticated/app/admin/imoveis/locacao/$id/editar': typeof AuthenticatedAppAdminImoveisLocacaoIdEditarRoute
  '/_authenticated/app/admin/imoveis/locacao/$id/': typeof AuthenticatedAppAdminImoveisLocacaoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmar-exclusao'
    | '/contato'
    | '/esqueci-senha'
    | '/historia'
    | '/login'
    | '/manifesto'
    | '/privacidade'
    | '/redefinir-senha'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/onboarding'
    | '/api/chat'
    | '/auth/confirmar'
    | '/blog/$slug'
    | '/blog/'
    | '/app/admin'
    | '/app/ajuda'
    | '/app/assinatura'
    | '/app/conta'
    | '/api/public/asaas-webhook'
    | '/api/public/auth-check'
    | '/api/public/demo-chat'
    | '/api/voz/falar'
    | '/api/voz/transcrever'
    | '/app/'
    | '/app/admin/auditoria'
    | '/app/admin/blog'
    | '/app/admin/cidades-novas'
    | '/app/admin/condominios'
    | '/app/admin/financeiro'
    | '/app/admin/imoveis'
    | '/app/admin/orientacoes'
    | '/app/admin/treinamento'
    | '/app/admin/uso'
    | '/app/ajuda/$secao'
    | '/app/ajuda/dicas-ia'
    | '/app/ajuda/faq'
    | '/app/assinatura/retorno'
    | '/app/condominios/$id'
    | '/app/suporte/$ticketId'
    | '/api/public/hooks/helpdesk-lembretes'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/app/admin/'
    | '/app/ajuda/'
    | '/app/condominios/'
    | '/app/admin/helpdesk/$ticketId'
    | '/app/admin/imoveis/importar'
    | '/app/admin/usuarios/$userId'
    | '/app/ajuda/perfil/$perfil'
    | '/app/admin/helpdesk/'
    | '/app/admin/imoveis/'
    | '/app/admin/usuarios/'
    | '/app/admin/imoveis/administracao/$id'
    | '/app/admin/imoveis/proprietarios/$id'
    | '/app/admin/imoveis/unidades/$id'
    | '/app/admin/imoveis/administracao/'
    | '/app/admin/imoveis/honorarios/'
    | '/app/admin/imoveis/locacao/'
    | '/app/admin/imoveis/proprietarios/'
    | '/app/admin/imoveis/unidades/'
    | '/app/admin/imoveis/locacao/$id/aditivo'
    | '/app/admin/imoveis/locacao/$id/editar'
    | '/app/admin/imoveis/locacao/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmar-exclusao'
    | '/contato'
    | '/esqueci-senha'
    | '/historia'
    | '/login'
    | '/manifesto'
    | '/privacidade'
    | '/redefinir-senha'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/onboarding'
    | '/api/chat'
    | '/auth/confirmar'
    | '/blog/$slug'
    | '/blog'
    | '/app/assinatura'
    | '/app/conta'
    | '/api/public/asaas-webhook'
    | '/api/public/auth-check'
    | '/api/public/demo-chat'
    | '/api/voz/falar'
    | '/api/voz/transcrever'
    | '/app'
    | '/app/admin/auditoria'
    | '/app/admin/blog'
    | '/app/admin/cidades-novas'
    | '/app/admin/condominios'
    | '/app/admin/financeiro'
    | '/app/admin/orientacoes'
    | '/app/admin/treinamento'
    | '/app/admin/uso'
    | '/app/ajuda/$secao'
    | '/app/ajuda/dicas-ia'
    | '/app/ajuda/faq'
    | '/app/assinatura/retorno'
    | '/app/condominios/$id'
    | '/app/suporte/$ticketId'
    | '/api/public/hooks/helpdesk-lembretes'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/app/admin'
    | '/app/ajuda'
    | '/app/condominios'
    | '/app/admin/helpdesk/$ticketId'
    | '/app/admin/imoveis/importar'
    | '/app/admin/usuarios/$userId'
    | '/app/ajuda/perfil/$perfil'
    | '/app/admin/helpdesk'
    | '/app/admin/imoveis'
    | '/app/admin/usuarios'
    | '/app/admin/imoveis/administracao/$id'
    | '/app/admin/imoveis/proprietarios/$id'
    | '/app/admin/imoveis/unidades/$id'
    | '/app/admin/imoveis/administracao'
    | '/app/admin/imoveis/honorarios'
    | '/app/admin/imoveis/locacao'
    | '/app/admin/imoveis/proprietarios'
    | '/app/admin/imoveis/unidades'
    | '/app/admin/imoveis/locacao/$id/aditivo'
    | '/app/admin/imoveis/locacao/$id/editar'
    | '/app/admin/imoveis/locacao/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/confirmar-exclusao'
    | '/contato'
    | '/esqueci-senha'
    | '/historia'
    | '/login'
    | '/manifesto'
    | '/privacidade'
    | '/redefinir-senha'
    | '/signup'
    | '/sitemap.xml'
    | '/termos'
    | '/_authenticated/onboarding'
    | '/api/chat'
    | '/auth/confirmar'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/ajuda'
    | '/_authenticated/app/assinatura'
    | '/_authenticated/app/conta'
    | '/api/public/asaas-webhook'
    | '/api/public/auth-check'
    | '/api/public/demo-chat'
    | '/api/voz/falar'
    | '/api/voz/transcrever'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/auditoria'
    | '/_authenticated/app/admin/blog'
    | '/_authenticated/app/admin/cidades-novas'
    | '/_authenticated/app/admin/condominios'
    | '/_authenticated/app/admin/financeiro'
    | '/_authenticated/app/admin/imoveis'
    | '/_authenticated/app/admin/orientacoes'
    | '/_authenticated/app/admin/treinamento'
    | '/_authenticated/app/admin/uso'
    | '/_authenticated/app/ajuda/$secao'
    | '/_authenticated/app/ajuda/dicas-ia'
    | '/_authenticated/app/ajuda/faq'
    | '/_authenticated/app/assinatura/retorno'
    | '/_authenticated/app/condominios/$id'
    | '/_authenticated/app/suporte/$ticketId'
    | '/api/public/hooks/helpdesk-lembretes'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/ajuda/'
    | '/_authenticated/app/condominios/'
    | '/_authenticated/app/admin/helpdesk/$ticketId'
    | '/_authenticated/app/admin/imoveis/importar'
    | '/_authenticated/app/admin/usuarios/$userId'
    | '/_authenticated/app/ajuda/perfil/$perfil'
    | '/_authenticated/app/admin/helpdesk/'
    | '/_authenticated/app/admin/imoveis/'
    | '/_authenticated/app/admin/usuarios/'
    | '/_authenticated/app/admin/imoveis/administracao/$id'
    | '/_authenticated/app/admin/imoveis/proprietarios/$id'
    | '/_authenticated/app/admin/imoveis/unidades/$id'
    | '/_authenticated/app/admin/imoveis/administracao/'
    | '/_authenticated/app/admin/imoveis/honorarios/'
    | '/_authenticated/app/admin/imoveis/locacao/'
    | '/_authenticated/app/admin/imoveis/proprietarios/'
    | '/_authenticated/app/admin/imoveis/unidades/'
    | '/_authenticated/app/admin/imoveis/locacao/$id/aditivo'
    | '/_authenticated/app/admin/imoveis/locacao/$id/editar'
    | '/_authenticated/app/admin/imoveis/locacao/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ConfirmarExclusaoRoute: typeof ConfirmarExclusaoRoute
  ContatoRoute: typeof ContatoRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  HistoriaRoute: typeof HistoriaRoute
  LoginRoute: typeof LoginRoute
  ManifestoRoute: typeof ManifestoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermosRoute: typeof TermosRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthConfirmarRoute: typeof AuthConfirmarRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicAuthCheckRoute: typeof ApiPublicAuthCheckRoute
  ApiPublicDemoChatRoute: typeof ApiPublicDemoChatRoute
  ApiVozFalarRoute: typeof ApiVozFalarRoute
  ApiVozTranscreverRoute: typeof ApiVozTranscreverRoute
  ApiPublicHooksHelpdeskLembretesRoute: typeof ApiPublicHooksHelpdeskLembretesRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-exclusao': {
      id: '/confirmar-exclusao'
      path: '/confirmar-exclusao'
      fullPath: '/confirmar-exclusao'
      preLoaderRoute: typeof ConfirmarExclusaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirmar': {
      id: '/auth/confirmar'
      path: '/auth/confirmar'
      fullPath: '/auth/confirmar'
      preLoaderRoute: typeof AuthConfirmarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/voz/transcrever': {
      id: '/api/voz/transcrever'
      path: '/api/voz/transcrever'
      fullPath: '/api/voz/transcrever'
      preLoaderRoute: typeof ApiVozTranscreverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voz/falar': {
      id: '/api/voz/falar'
      path: '/api/voz/falar'
      fullPath: '/api/voz/falar'
      preLoaderRoute: typeof ApiVozFalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/demo-chat': {
      id: '/api/public/demo-chat'
      path: '/api/public/demo-chat'
      fullPath: '/api/public/demo-chat'
      preLoaderRoute: typeof ApiPublicDemoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-check': {
      id: '/api/public/auth-check'
      path: '/api/public/auth-check'
      fullPath: '/api/public/auth-check'
      preLoaderRoute: typeof ApiPublicAuthCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/conta': {
      id: '/_authenticated/app/conta'
      path: '/app/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AuthenticatedAppContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/assinatura': {
      id: '/_authenticated/app/assinatura'
      path: '/app/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AuthenticatedAppAssinaturaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ajuda': {
      id: '/_authenticated/app/ajuda'
      path: '/app/ajuda'
      fullPath: '/app/ajuda'
      preLoaderRoute: typeof AuthenticatedAppAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/condominios/': {
      id: '/_authenticated/app/condominios/'
      path: '/app/condominios'
      fullPath: '/app/condominios/'
      preLoaderRoute: typeof AuthenticatedAppCondominiosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ajuda/': {
      id: '/_authenticated/app/ajuda/'
      path: '/'
      fullPath: '/app/ajuda/'
      preLoaderRoute: typeof AuthenticatedAppAjudaIndexRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/helpdesk-lembretes': {
      id: '/api/public/hooks/helpdesk-lembretes'
      path: '/api/public/hooks/helpdesk-lembretes'
      fullPath: '/api/public/hooks/helpdesk-lembretes'
      preLoaderRoute: typeof ApiPublicHooksHelpdeskLembretesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/suporte/$ticketId': {
      id: '/_authenticated/app/suporte/$ticketId'
      path: '/app/suporte/$ticketId'
      fullPath: '/app/suporte/$ticketId'
      preLoaderRoute: typeof AuthenticatedAppSuporteTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/condominios/$id': {
      id: '/_authenticated/app/condominios/$id'
      path: '/app/condominios/$id'
      fullPath: '/app/condominios/$id'
      preLoaderRoute: typeof AuthenticatedAppCondominiosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/assinatura/retorno': {
      id: '/_authenticated/app/assinatura/retorno'
      path: '/retorno'
      fullPath: '/app/assinatura/retorno'
      preLoaderRoute: typeof AuthenticatedAppAssinaturaRetornoRouteImport
      parentRoute: typeof AuthenticatedAppAssinaturaRoute
    }
    '/_authenticated/app/ajuda/faq': {
      id: '/_authenticated/app/ajuda/faq'
      path: '/faq'
      fullPath: '/app/ajuda/faq'
      preLoaderRoute: typeof AuthenticatedAppAjudaFaqRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/ajuda/dicas-ia': {
      id: '/_authenticated/app/ajuda/dicas-ia'
      path: '/dicas-ia'
      fullPath: '/app/ajuda/dicas-ia'
      preLoaderRoute: typeof AuthenticatedAppAjudaDicasIaRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/ajuda/$secao': {
      id: '/_authenticated/app/ajuda/$secao'
      path: '/$secao'
      fullPath: '/app/ajuda/$secao'
      preLoaderRoute: typeof AuthenticatedAppAjudaSecaoRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/admin/uso': {
      id: '/_authenticated/app/admin/uso'
      path: '/uso'
      fullPath: '/app/admin/uso'
      preLoaderRoute: typeof AuthenticatedAppAdminUsoRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/treinamento': {
      id: '/_authenticated/app/admin/treinamento'
      path: '/treinamento'
      fullPath: '/app/admin/treinamento'
      preLoaderRoute: typeof AuthenticatedAppAdminTreinamentoRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/orientacoes': {
      id: '/_authenticated/app/admin/orientacoes'
      path: '/orientacoes'
      fullPath: '/app/admin/orientacoes'
      preLoaderRoute: typeof AuthenticatedAppAdminOrientacoesRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/imoveis': {
      id: '/_authenticated/app/admin/imoveis'
      path: '/imoveis'
      fullPath: '/app/admin/imoveis'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/financeiro': {
      id: '/_authenticated/app/admin/financeiro'
      path: '/financeiro'
      fullPath: '/app/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAppAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/condominios': {
      id: '/_authenticated/app/admin/condominios'
      path: '/condominios'
      fullPath: '/app/admin/condominios'
      preLoaderRoute: typeof AuthenticatedAppAdminCondominiosRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/cidades-novas': {
      id: '/_authenticated/app/admin/cidades-novas'
      path: '/cidades-novas'
      fullPath: '/app/admin/cidades-novas'
      preLoaderRoute: typeof AuthenticatedAppAdminCidadesNovasRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/blog': {
      id: '/_authenticated/app/admin/blog'
      path: '/blog'
      fullPath: '/app/admin/blog'
      preLoaderRoute: typeof AuthenticatedAppAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/auditoria': {
      id: '/_authenticated/app/admin/auditoria'
      path: '/auditoria'
      fullPath: '/app/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAppAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/usuarios/': {
      id: '/_authenticated/app/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/app/admin/usuarios/'
      preLoaderRoute: typeof AuthenticatedAppAdminUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/imoveis/': {
      id: '/_authenticated/app/admin/imoveis/'
      path: '/'
      fullPath: '/app/admin/imoveis/'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/helpdesk/': {
      id: '/_authenticated/app/admin/helpdesk/'
      path: '/helpdesk'
      fullPath: '/app/admin/helpdesk/'
      preLoaderRoute: typeof AuthenticatedAppAdminHelpdeskIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/ajuda/perfil/$perfil': {
      id: '/_authenticated/app/ajuda/perfil/$perfil'
      path: '/perfil/$perfil'
      fullPath: '/app/ajuda/perfil/$perfil'
      preLoaderRoute: typeof AuthenticatedAppAjudaPerfilPerfilRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/admin/usuarios/$userId': {
      id: '/_authenticated/app/admin/usuarios/$userId'
      path: '/usuarios/$userId'
      fullPath: '/app/admin/usuarios/$userId'
      preLoaderRoute: typeof AuthenticatedAppAdminUsuariosUserIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/imoveis/importar': {
      id: '/_authenticated/app/admin/imoveis/importar'
      path: '/importar'
      fullPath: '/app/admin/imoveis/importar'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisImportarRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/helpdesk/$ticketId': {
      id: '/_authenticated/app/admin/helpdesk/$ticketId'
      path: '/helpdesk/$ticketId'
      fullPath: '/app/admin/helpdesk/$ticketId'
      preLoaderRoute: typeof AuthenticatedAppAdminHelpdeskTicketIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/imoveis/unidades/': {
      id: '/_authenticated/app/admin/imoveis/unidades/'
      path: '/unidades'
      fullPath: '/app/admin/imoveis/unidades/'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisUnidadesIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/proprietarios/': {
      id: '/_authenticated/app/admin/imoveis/proprietarios/'
      path: '/proprietarios'
      fullPath: '/app/admin/imoveis/proprietarios/'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisProprietariosIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/locacao/': {
      id: '/_authenticated/app/admin/imoveis/locacao/'
      path: '/locacao'
      fullPath: '/app/admin/imoveis/locacao/'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisLocacaoIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/honorarios/': {
      id: '/_authenticated/app/admin/imoveis/honorarios/'
      path: '/honorarios'
      fullPath: '/app/admin/imoveis/honorarios/'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisHonorariosIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/administracao/': {
      id: '/_authenticated/app/admin/imoveis/administracao/'
      path: '/administracao'
      fullPath: '/app/admin/imoveis/administracao/'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisAdministracaoIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/unidades/$id': {
      id: '/_authenticated/app/admin/imoveis/unidades/$id'
      path: '/unidades/$id'
      fullPath: '/app/admin/imoveis/unidades/$id'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisUnidadesIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/proprietarios/$id': {
      id: '/_authenticated/app/admin/imoveis/proprietarios/$id'
      path: '/proprietarios/$id'
      fullPath: '/app/admin/imoveis/proprietarios/$id'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisProprietariosIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/administracao/$id': {
      id: '/_authenticated/app/admin/imoveis/administracao/$id'
      path: '/administracao/$id'
      fullPath: '/app/admin/imoveis/administracao/$id'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisAdministracaoIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/locacao/$id/': {
      id: '/_authenticated/app/admin/imoveis/locacao/$id/'
      path: '/locacao/$id'
      fullPath: '/app/admin/imoveis/locacao/$id/'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisLocacaoIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/locacao/$id/editar': {
      id: '/_authenticated/app/admin/imoveis/locacao/$id/editar'
      path: '/locacao/$id/editar'
      fullPath: '/app/admin/imoveis/locacao/$id/editar'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisLocacaoIdEditarRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
    '/_authenticated/app/admin/imoveis/locacao/$id/aditivo': {
      id: '/_authenticated/app/admin/imoveis/locacao/$id/aditivo'
      path: '/locacao/$id/aditivo'
      fullPath: '/app/admin/imoveis/locacao/$id/aditivo'
      preLoaderRoute: typeof AuthenticatedAppAdminImoveisLocacaoIdAditivoRouteImport
      parentRoute: typeof AuthenticatedAppAdminImoveisRoute
    }
  }
}

interface AuthenticatedAppAdminImoveisRouteChildren {
  AuthenticatedAppAdminImoveisImportarRoute: typeof AuthenticatedAppAdminImoveisImportarRoute
  AuthenticatedAppAdminImoveisIndexRoute: typeof AuthenticatedAppAdminImoveisIndexRoute
  AuthenticatedAppAdminImoveisAdministracaoIdRoute: typeof AuthenticatedAppAdminImoveisAdministracaoIdRoute
  AuthenticatedAppAdminImoveisProprietariosIdRoute: typeof AuthenticatedAppAdminImoveisProprietariosIdRoute
  AuthenticatedAppAdminImoveisUnidadesIdRoute: typeof AuthenticatedAppAdminImoveisUnidadesIdRoute
  AuthenticatedAppAdminImoveisAdministracaoIndexRoute: typeof AuthenticatedAppAdminImoveisAdministracaoIndexRoute
  AuthenticatedAppAdminImoveisHonorariosIndexRoute: typeof AuthenticatedAppAdminImoveisHonorariosIndexRoute
  AuthenticatedAppAdminImoveisLocacaoIndexRoute: typeof AuthenticatedAppAdminImoveisLocacaoIndexRoute
  AuthenticatedAppAdminImoveisProprietariosIndexRoute: typeof AuthenticatedAppAdminImoveisProprietariosIndexRoute
  AuthenticatedAppAdminImoveisUnidadesIndexRoute: typeof AuthenticatedAppAdminImoveisUnidadesIndexRoute
  AuthenticatedAppAdminImoveisLocacaoIdAditivoRoute: typeof AuthenticatedAppAdminImoveisLocacaoIdAditivoRoute
  AuthenticatedAppAdminImoveisLocacaoIdEditarRoute: typeof AuthenticatedAppAdminImoveisLocacaoIdEditarRoute
  AuthenticatedAppAdminImoveisLocacaoIdIndexRoute: typeof AuthenticatedAppAdminImoveisLocacaoIdIndexRoute
}

const AuthenticatedAppAdminImoveisRouteChildren: AuthenticatedAppAdminImoveisRouteChildren =
  {
    AuthenticatedAppAdminImoveisImportarRoute:
      AuthenticatedAppAdminImoveisImportarRoute,
    AuthenticatedAppAdminImoveisIndexRoute:
      AuthenticatedAppAdminImoveisIndexRoute,
    AuthenticatedAppAdminImoveisAdministracaoIdRoute:
      AuthenticatedAppAdminImoveisAdministracaoIdRoute,
    AuthenticatedAppAdminImoveisProprietariosIdRoute:
      AuthenticatedAppAdminImoveisProprietariosIdRoute,
    AuthenticatedAppAdminImoveisUnidadesIdRoute:
      AuthenticatedAppAdminImoveisUnidadesIdRoute,
    AuthenticatedAppAdminImoveisAdministracaoIndexRoute:
      AuthenticatedAppAdminImoveisAdministracaoIndexRoute,
    AuthenticatedAppAdminImoveisHonorariosIndexRoute:
      AuthenticatedAppAdminImoveisHonorariosIndexRoute,
    AuthenticatedAppAdminImoveisLocacaoIndexRoute:
      AuthenticatedAppAdminImoveisLocacaoIndexRoute,
    AuthenticatedAppAdminImoveisProprietariosIndexRoute:
      AuthenticatedAppAdminImoveisProprietariosIndexRoute,
    AuthenticatedAppAdminImoveisUnidadesIndexRoute:
      AuthenticatedAppAdminImoveisUnidadesIndexRoute,
    AuthenticatedAppAdminImoveisLocacaoIdAditivoRoute:
      AuthenticatedAppAdminImoveisLocacaoIdAditivoRoute,
    AuthenticatedAppAdminImoveisLocacaoIdEditarRoute:
      AuthenticatedAppAdminImoveisLocacaoIdEditarRoute,
    AuthenticatedAppAdminImoveisLocacaoIdIndexRoute:
      AuthenticatedAppAdminImoveisLocacaoIdIndexRoute,
  }

const AuthenticatedAppAdminImoveisRouteWithChildren =
  AuthenticatedAppAdminImoveisRoute._addFileChildren(
    AuthenticatedAppAdminImoveisRouteChildren,
  )

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminAuditoriaRoute: typeof AuthenticatedAppAdminAuditoriaRoute
  AuthenticatedAppAdminBlogRoute: typeof AuthenticatedAppAdminBlogRoute
  AuthenticatedAppAdminCidadesNovasRoute: typeof AuthenticatedAppAdminCidadesNovasRoute
  AuthenticatedAppAdminCondominiosRoute: typeof AuthenticatedAppAdminCondominiosRoute
  AuthenticatedAppAdminFinanceiroRoute: typeof AuthenticatedAppAdminFinanceiroRoute
  AuthenticatedAppAdminImoveisRoute: typeof AuthenticatedAppAdminImoveisRouteWithChildren
  AuthenticatedAppAdminOrientacoesRoute: typeof AuthenticatedAppAdminOrientacoesRoute
  AuthenticatedAppAdminTreinamentoRoute: typeof AuthenticatedAppAdminTreinamentoRoute
  AuthenticatedAppAdminUsoRoute: typeof AuthenticatedAppAdminUsoRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
  AuthenticatedAppAdminHelpdeskTicketIdRoute: typeof AuthenticatedAppAdminHelpdeskTicketIdRoute
  AuthenticatedAppAdminUsuariosUserIdRoute: typeof AuthenticatedAppAdminUsuariosUserIdRoute
  AuthenticatedAppAdminHelpdeskIndexRoute: typeof AuthenticatedAppAdminHelpdeskIndexRoute
  AuthenticatedAppAdminUsuariosIndexRoute: typeof AuthenticatedAppAdminUsuariosIndexRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminAuditoriaRoute: AuthenticatedAppAdminAuditoriaRoute,
  AuthenticatedAppAdminBlogRoute: AuthenticatedAppAdminBlogRoute,
  AuthenticatedAppAdminCidadesNovasRoute:
    AuthenticatedAppAdminCidadesNovasRoute,
  AuthenticatedAppAdminCondominiosRoute: AuthenticatedAppAdminCondominiosRoute,
  AuthenticatedAppAdminFinanceiroRoute: AuthenticatedAppAdminFinanceiroRoute,
  AuthenticatedAppAdminImoveisRoute:
    AuthenticatedAppAdminImoveisRouteWithChildren,
  AuthenticatedAppAdminOrientacoesRoute: AuthenticatedAppAdminOrientacoesRoute,
  AuthenticatedAppAdminTreinamentoRoute: AuthenticatedAppAdminTreinamentoRoute,
  AuthenticatedAppAdminUsoRoute: AuthenticatedAppAdminUsoRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
  AuthenticatedAppAdminHelpdeskTicketIdRoute:
    AuthenticatedAppAdminHelpdeskTicketIdRoute,
  AuthenticatedAppAdminUsuariosUserIdRoute:
    AuthenticatedAppAdminUsuariosUserIdRoute,
  AuthenticatedAppAdminHelpdeskIndexRoute:
    AuthenticatedAppAdminHelpdeskIndexRoute,
  AuthenticatedAppAdminUsuariosIndexRoute:
    AuthenticatedAppAdminUsuariosIndexRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppAjudaRouteChildren {
  AuthenticatedAppAjudaSecaoRoute: typeof AuthenticatedAppAjudaSecaoRoute
  AuthenticatedAppAjudaDicasIaRoute: typeof AuthenticatedAppAjudaDicasIaRoute
  AuthenticatedAppAjudaFaqRoute: typeof AuthenticatedAppAjudaFaqRoute
  AuthenticatedAppAjudaIndexRoute: typeof AuthenticatedAppAjudaIndexRoute
  AuthenticatedAppAjudaPerfilPerfilRoute: typeof AuthenticatedAppAjudaPerfilPerfilRoute
}

const AuthenticatedAppAjudaRouteChildren: AuthenticatedAppAjudaRouteChildren = {
  AuthenticatedAppAjudaSecaoRoute: AuthenticatedAppAjudaSecaoRoute,
  AuthenticatedAppAjudaDicasIaRoute: AuthenticatedAppAjudaDicasIaRoute,
  AuthenticatedAppAjudaFaqRoute: AuthenticatedAppAjudaFaqRoute,
  AuthenticatedAppAjudaIndexRoute: AuthenticatedAppAjudaIndexRoute,
  AuthenticatedAppAjudaPerfilPerfilRoute:
    AuthenticatedAppAjudaPerfilPerfilRoute,
}

const AuthenticatedAppAjudaRouteWithChildren =
  AuthenticatedAppAjudaRoute._addFileChildren(
    AuthenticatedAppAjudaRouteChildren,
  )

interface AuthenticatedAppAssinaturaRouteChildren {
  AuthenticatedAppAssinaturaRetornoRoute: typeof AuthenticatedAppAssinaturaRetornoRoute
}

const AuthenticatedAppAssinaturaRouteChildren: AuthenticatedAppAssinaturaRouteChildren =
  {
    AuthenticatedAppAssinaturaRetornoRoute:
      AuthenticatedAppAssinaturaRetornoRoute,
  }

const AuthenticatedAppAssinaturaRouteWithChildren =
  AuthenticatedAppAssinaturaRoute._addFileChildren(
    AuthenticatedAppAssinaturaRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppAjudaRoute: typeof AuthenticatedAppAjudaRouteWithChildren
  AuthenticatedAppAssinaturaRoute: typeof AuthenticatedAppAssinaturaRouteWithChildren
  AuthenticatedAppContaRoute: typeof AuthenticatedAppContaRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCondominiosIdRoute: typeof AuthenticatedAppCondominiosIdRoute
  AuthenticatedAppSuporteTicketIdRoute: typeof AuthenticatedAppSuporteTicketIdRoute
  AuthenticatedAppCondominiosIndexRoute: typeof AuthenticatedAppCondominiosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppAjudaRoute: AuthenticatedAppAjudaRouteWithChildren,
  AuthenticatedAppAssinaturaRoute: AuthenticatedAppAssinaturaRouteWithChildren,
  AuthenticatedAppContaRoute: AuthenticatedAppContaRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCondominiosIdRoute: AuthenticatedAppCondominiosIdRoute,
  AuthenticatedAppSuporteTicketIdRoute: AuthenticatedAppSuporteTicketIdRoute,
  AuthenticatedAppCondominiosIndexRoute: AuthenticatedAppCondominiosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ConfirmarExclusaoRoute: ConfirmarExclusaoRoute,
  ContatoRoute: ContatoRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  HistoriaRoute: HistoriaRoute,
  LoginRoute: LoginRoute,
  ManifestoRoute: ManifestoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermosRoute: TermosRoute,
  ApiChatRoute: ApiChatRoute,
  AuthConfirmarRoute: AuthConfirmarRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicAuthCheckRoute: ApiPublicAuthCheckRoute,
  ApiPublicDemoChatRoute: ApiPublicDemoChatRoute,
  ApiVozFalarRoute: ApiVozFalarRoute,
  ApiVozTranscreverRoute: ApiVozTranscreverRoute,
  ApiPublicHooksHelpdeskLembretesRoute: ApiPublicHooksHelpdeskLembretesRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
