/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppContaRouteImport } from './routes/_authenticated/app.conta'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppCondominiosIndexRouteImport } from './routes/_authenticated/app.condominios.index'
import { Route as AuthenticatedAppCondominiosIdRouteImport } from './routes/_authenticated/app.condominios.$id'
import { Route as AuthenticatedAppAdminUsuariosRouteImport } from './routes/_authenticated/app.admin.usuarios'
import { Route as AuthenticatedAppAdminCondominiosRouteImport } from './routes/_authenticated/app.admin.condominios'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppContaRoute = AuthenticatedAppContaRouteImport.update({
  id: '/app/conta',
  path: '/app/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCondominiosIndexRoute =
  AuthenticatedAppCondominiosIndexRouteImport.update({
    id: '/app/condominios/',
    path: '/app/condominios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppCondominiosIdRoute =
  AuthenticatedAppCondominiosIdRouteImport.update({
    id: '/app/condominios/$id',
    path: '/app/condominios/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAdminUsuariosRoute =
  AuthenticatedAppAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminCondominiosRoute =
  AuthenticatedAppAdminCondominiosRouteImport.update({
    id: '/condominios',
    path: '/condominios',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/condominios': typeof AuthenticatedAppAdminCondominiosRoute
  '/app/admin/usuarios': typeof AuthenticatedAppAdminUsuariosRoute
  '/app/condominios/$id': typeof AuthenticatedAppCondominiosIdRoute
  '/app/condominios/': typeof AuthenticatedAppCondominiosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/api/chat': typeof ApiChatRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/condominios': typeof AuthenticatedAppAdminCondominiosRoute
  '/app/admin/usuarios': typeof AuthenticatedAppAdminUsuariosRoute
  '/app/condominios/$id': typeof AuthenticatedAppCondominiosIdRoute
  '/app/condominios': typeof AuthenticatedAppCondominiosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/conta': typeof AuthenticatedAppContaRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/condominios': typeof AuthenticatedAppAdminCondominiosRoute
  '/_authenticated/app/admin/usuarios': typeof AuthenticatedAppAdminUsuariosRoute
  '/_authenticated/app/condominios/$id': typeof AuthenticatedAppCondominiosIdRoute
  '/_authenticated/app/condominios/': typeof AuthenticatedAppCondominiosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/privacidade'
    | '/signup'
    | '/termos'
    | '/api/chat'
    | '/app/admin'
    | '/app/conta'
    | '/app/'
    | '/app/admin/condominios'
    | '/app/admin/usuarios'
    | '/app/condominios/$id'
    | '/app/condominios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/privacidade'
    | '/signup'
    | '/termos'
    | '/api/chat'
    | '/app/admin'
    | '/app/conta'
    | '/app'
    | '/app/admin/condominios'
    | '/app/admin/usuarios'
    | '/app/condominios/$id'
    | '/app/condominios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/privacidade'
    | '/signup'
    | '/termos'
    | '/api/chat'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/conta'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/condominios'
    | '/_authenticated/app/admin/usuarios'
    | '/_authenticated/app/condominios/$id'
    | '/_authenticated/app/condominios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/conta': {
      id: '/_authenticated/app/conta'
      path: '/app/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AuthenticatedAppContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/condominios/': {
      id: '/_authenticated/app/condominios/'
      path: '/app/condominios'
      fullPath: '/app/condominios/'
      preLoaderRoute: typeof AuthenticatedAppCondominiosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/condominios/$id': {
      id: '/_authenticated/app/condominios/$id'
      path: '/app/condominios/$id'
      fullPath: '/app/condominios/$id'
      preLoaderRoute: typeof AuthenticatedAppCondominiosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin/usuarios': {
      id: '/_authenticated/app/admin/usuarios'
      path: '/usuarios'
      fullPath: '/app/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAppAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/condominios': {
      id: '/_authenticated/app/admin/condominios'
      path: '/condominios'
      fullPath: '/app/admin/condominios'
      preLoaderRoute: typeof AuthenticatedAppAdminCondominiosRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminCondominiosRoute: typeof AuthenticatedAppAdminCondominiosRoute
  AuthenticatedAppAdminUsuariosRoute: typeof AuthenticatedAppAdminUsuariosRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminCondominiosRoute: AuthenticatedAppAdminCondominiosRoute,
  AuthenticatedAppAdminUsuariosRoute: AuthenticatedAppAdminUsuariosRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppContaRoute: typeof AuthenticatedAppContaRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCondominiosIdRoute: typeof AuthenticatedAppCondominiosIdRoute
  AuthenticatedAppCondominiosIndexRoute: typeof AuthenticatedAppCondominiosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppContaRoute: AuthenticatedAppContaRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCondominiosIdRoute: AuthenticatedAppCondominiosIdRoute,
  AuthenticatedAppCondominiosIndexRoute: AuthenticatedAppCondominiosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
