/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ManifestoRouteImport } from './routes/manifesto'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as ApiPublicDemoChatRouteImport } from './routes/api/public/demo-chat'
import { Route as AuthenticatedAppContaRouteImport } from './routes/_authenticated/app.conta'
import { Route as AuthenticatedAppAjudaRouteImport } from './routes/_authenticated/app.ajuda'
import { Route as AuthenticatedAppAdminRouteImport } from './routes/_authenticated/app.admin'
import { Route as AuthenticatedAppCondominiosIndexRouteImport } from './routes/_authenticated/app.condominios.index'
import { Route as AuthenticatedAppAjudaIndexRouteImport } from './routes/_authenticated/app.ajuda.index'
import { Route as AuthenticatedAppAdminIndexRouteImport } from './routes/_authenticated/app.admin.index'
import { Route as AuthenticatedAppCondominiosIdRouteImport } from './routes/_authenticated/app.condominios.$id'
import { Route as AuthenticatedAppAjudaFaqRouteImport } from './routes/_authenticated/app.ajuda.faq'
import { Route as AuthenticatedAppAjudaDicasIaRouteImport } from './routes/_authenticated/app.ajuda.dicas-ia'
import { Route as AuthenticatedAppAjudaSecaoRouteImport } from './routes/_authenticated/app.ajuda.$secao'
import { Route as AuthenticatedAppAdminUsoRouteImport } from './routes/_authenticated/app.admin.uso'
import { Route as AuthenticatedAppAdminTreinamentoRouteImport } from './routes/_authenticated/app.admin.treinamento'
import { Route as AuthenticatedAppAdminOrientacoesRouteImport } from './routes/_authenticated/app.admin.orientacoes'
import { Route as AuthenticatedAppAdminFinanceiroRouteImport } from './routes/_authenticated/app.admin.financeiro'
import { Route as AuthenticatedAppAdminCondominiosRouteImport } from './routes/_authenticated/app.admin.condominios'
import { Route as AuthenticatedAppAdminBlogRouteImport } from './routes/_authenticated/app.admin.blog'
import { Route as AuthenticatedAppAdminAuditoriaRouteImport } from './routes/_authenticated/app.admin.auditoria'
import { Route as AuthenticatedAppAdminUsuariosIndexRouteImport } from './routes/_authenticated/app.admin.usuarios.index'
import { Route as AuthenticatedAppAjudaPerfilPerfilRouteImport } from './routes/_authenticated/app.ajuda.perfil.$perfil'
import { Route as AuthenticatedAppAdminUsuariosUserIdRouteImport } from './routes/_authenticated/app.admin.usuarios.$userId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestoRoute = ManifestoRouteImport.update({
  id: '/manifesto',
  path: '/manifesto',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicDemoChatRoute = ApiPublicDemoChatRouteImport.update({
  id: '/api/public/demo-chat',
  path: '/api/public/demo-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppContaRoute = AuthenticatedAppContaRouteImport.update({
  id: '/app/conta',
  path: '/app/conta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAjudaRoute = AuthenticatedAppAjudaRouteImport.update({
  id: '/app/ajuda',
  path: '/app/ajuda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppAdminRoute = AuthenticatedAppAdminRouteImport.update({
  id: '/app/admin',
  path: '/app/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppCondominiosIndexRoute =
  AuthenticatedAppCondominiosIndexRouteImport.update({
    id: '/app/condominios/',
    path: '/app/condominios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAjudaIndexRoute =
  AuthenticatedAppAjudaIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAdminIndexRoute =
  AuthenticatedAppAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppCondominiosIdRoute =
  AuthenticatedAppCondominiosIdRouteImport.update({
    id: '/app/condominios/$id',
    path: '/app/condominios/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppAjudaFaqRoute =
  AuthenticatedAppAjudaFaqRouteImport.update({
    id: '/faq',
    path: '/faq',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAjudaDicasIaRoute =
  AuthenticatedAppAjudaDicasIaRouteImport.update({
    id: '/dicas-ia',
    path: '/dicas-ia',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAjudaSecaoRoute =
  AuthenticatedAppAjudaSecaoRouteImport.update({
    id: '/$secao',
    path: '/$secao',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAdminUsoRoute =
  AuthenticatedAppAdminUsoRouteImport.update({
    id: '/uso',
    path: '/uso',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminTreinamentoRoute =
  AuthenticatedAppAdminTreinamentoRouteImport.update({
    id: '/treinamento',
    path: '/treinamento',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminOrientacoesRoute =
  AuthenticatedAppAdminOrientacoesRouteImport.update({
    id: '/orientacoes',
    path: '/orientacoes',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminFinanceiroRoute =
  AuthenticatedAppAdminFinanceiroRouteImport.update({
    id: '/financeiro',
    path: '/financeiro',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminCondominiosRoute =
  AuthenticatedAppAdminCondominiosRouteImport.update({
    id: '/condominios',
    path: '/condominios',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminBlogRoute =
  AuthenticatedAppAdminBlogRouteImport.update({
    id: '/blog',
    path: '/blog',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminAuditoriaRoute =
  AuthenticatedAppAdminAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAdminUsuariosIndexRoute =
  AuthenticatedAppAdminUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)
const AuthenticatedAppAjudaPerfilPerfilRoute =
  AuthenticatedAppAjudaPerfilPerfilRouteImport.update({
    id: '/perfil/$perfil',
    path: '/perfil/$perfil',
    getParentRoute: () => AuthenticatedAppAjudaRoute,
  } as any)
const AuthenticatedAppAdminUsuariosUserIdRoute =
  AuthenticatedAppAdminUsuariosUserIdRouteImport.update({
    id: '/usuarios/$userId',
    path: '/usuarios/$userId',
    getParentRoute: () => AuthenticatedAppAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/app/ajuda': typeof AuthenticatedAppAjudaRouteWithChildren
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/admin/auditoria': typeof AuthenticatedAppAdminAuditoriaRoute
  '/app/admin/blog': typeof AuthenticatedAppAdminBlogRoute
  '/app/admin/condominios': typeof AuthenticatedAppAdminCondominiosRoute
  '/app/admin/financeiro': typeof AuthenticatedAppAdminFinanceiroRoute
  '/app/admin/orientacoes': typeof AuthenticatedAppAdminOrientacoesRoute
  '/app/admin/treinamento': typeof AuthenticatedAppAdminTreinamentoRoute
  '/app/admin/uso': typeof AuthenticatedAppAdminUsoRoute
  '/app/ajuda/$secao': typeof AuthenticatedAppAjudaSecaoRoute
  '/app/ajuda/dicas-ia': typeof AuthenticatedAppAjudaDicasIaRoute
  '/app/ajuda/faq': typeof AuthenticatedAppAjudaFaqRoute
  '/app/condominios/$id': typeof AuthenticatedAppCondominiosIdRoute
  '/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/app/ajuda/': typeof AuthenticatedAppAjudaIndexRoute
  '/app/condominios/': typeof AuthenticatedAppCondominiosIndexRoute
  '/app/admin/usuarios/$userId': typeof AuthenticatedAppAdminUsuariosUserIdRoute
  '/app/ajuda/perfil/$perfil': typeof AuthenticatedAppAjudaPerfilPerfilRoute
  '/app/admin/usuarios/': typeof AuthenticatedAppAdminUsuariosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/app/conta': typeof AuthenticatedAppContaRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/admin/auditoria': typeof AuthenticatedAppAdminAuditoriaRoute
  '/app/admin/blog': typeof AuthenticatedAppAdminBlogRoute
  '/app/admin/condominios': typeof AuthenticatedAppAdminCondominiosRoute
  '/app/admin/financeiro': typeof AuthenticatedAppAdminFinanceiroRoute
  '/app/admin/orientacoes': typeof AuthenticatedAppAdminOrientacoesRoute
  '/app/admin/treinamento': typeof AuthenticatedAppAdminTreinamentoRoute
  '/app/admin/uso': typeof AuthenticatedAppAdminUsoRoute
  '/app/ajuda/$secao': typeof AuthenticatedAppAjudaSecaoRoute
  '/app/ajuda/dicas-ia': typeof AuthenticatedAppAjudaDicasIaRoute
  '/app/ajuda/faq': typeof AuthenticatedAppAjudaFaqRoute
  '/app/condominios/$id': typeof AuthenticatedAppCondominiosIdRoute
  '/app/admin': typeof AuthenticatedAppAdminIndexRoute
  '/app/ajuda': typeof AuthenticatedAppAjudaIndexRoute
  '/app/condominios': typeof AuthenticatedAppCondominiosIndexRoute
  '/app/admin/usuarios/$userId': typeof AuthenticatedAppAdminUsuariosUserIdRoute
  '/app/ajuda/perfil/$perfil': typeof AuthenticatedAppAjudaPerfilPerfilRoute
  '/app/admin/usuarios': typeof AuthenticatedAppAdminUsuariosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/historia': typeof HistoriaRoute
  '/login': typeof LoginRoute
  '/manifesto': typeof ManifestoRoute
  '/privacidade': typeof PrivacidadeRoute
  '/signup': typeof SignupRoute
  '/termos': typeof TermosRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/app/admin': typeof AuthenticatedAppAdminRouteWithChildren
  '/_authenticated/app/ajuda': typeof AuthenticatedAppAjudaRouteWithChildren
  '/_authenticated/app/conta': typeof AuthenticatedAppContaRoute
  '/api/public/demo-chat': typeof ApiPublicDemoChatRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/admin/auditoria': typeof AuthenticatedAppAdminAuditoriaRoute
  '/_authenticated/app/admin/blog': typeof AuthenticatedAppAdminBlogRoute
  '/_authenticated/app/admin/condominios': typeof AuthenticatedAppAdminCondominiosRoute
  '/_authenticated/app/admin/financeiro': typeof AuthenticatedAppAdminFinanceiroRoute
  '/_authenticated/app/admin/orientacoes': typeof AuthenticatedAppAdminOrientacoesRoute
  '/_authenticated/app/admin/treinamento': typeof AuthenticatedAppAdminTreinamentoRoute
  '/_authenticated/app/admin/uso': typeof AuthenticatedAppAdminUsoRoute
  '/_authenticated/app/ajuda/$secao': typeof AuthenticatedAppAjudaSecaoRoute
  '/_authenticated/app/ajuda/dicas-ia': typeof AuthenticatedAppAjudaDicasIaRoute
  '/_authenticated/app/ajuda/faq': typeof AuthenticatedAppAjudaFaqRoute
  '/_authenticated/app/condominios/$id': typeof AuthenticatedAppCondominiosIdRoute
  '/_authenticated/app/admin/': typeof AuthenticatedAppAdminIndexRoute
  '/_authenticated/app/ajuda/': typeof AuthenticatedAppAjudaIndexRoute
  '/_authenticated/app/condominios/': typeof AuthenticatedAppCondominiosIndexRoute
  '/_authenticated/app/admin/usuarios/$userId': typeof AuthenticatedAppAdminUsuariosUserIdRoute
  '/_authenticated/app/ajuda/perfil/$perfil': typeof AuthenticatedAppAjudaPerfilPerfilRoute
  '/_authenticated/app/admin/usuarios/': typeof AuthenticatedAppAdminUsuariosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/historia'
    | '/login'
    | '/manifesto'
    | '/privacidade'
    | '/signup'
    | '/termos'
    | '/onboarding'
    | '/api/chat'
    | '/blog/$slug'
    | '/blog/'
    | '/app/admin'
    | '/app/ajuda'
    | '/app/conta'
    | '/api/public/demo-chat'
    | '/app/'
    | '/app/admin/auditoria'
    | '/app/admin/blog'
    | '/app/admin/condominios'
    | '/app/admin/financeiro'
    | '/app/admin/orientacoes'
    | '/app/admin/treinamento'
    | '/app/admin/uso'
    | '/app/ajuda/$secao'
    | '/app/ajuda/dicas-ia'
    | '/app/ajuda/faq'
    | '/app/condominios/$id'
    | '/app/admin/'
    | '/app/ajuda/'
    | '/app/condominios/'
    | '/app/admin/usuarios/$userId'
    | '/app/ajuda/perfil/$perfil'
    | '/app/admin/usuarios/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/historia'
    | '/login'
    | '/manifesto'
    | '/privacidade'
    | '/signup'
    | '/termos'
    | '/onboarding'
    | '/api/chat'
    | '/blog/$slug'
    | '/blog'
    | '/app/conta'
    | '/api/public/demo-chat'
    | '/app'
    | '/app/admin/auditoria'
    | '/app/admin/blog'
    | '/app/admin/condominios'
    | '/app/admin/financeiro'
    | '/app/admin/orientacoes'
    | '/app/admin/treinamento'
    | '/app/admin/uso'
    | '/app/ajuda/$secao'
    | '/app/ajuda/dicas-ia'
    | '/app/ajuda/faq'
    | '/app/condominios/$id'
    | '/app/admin'
    | '/app/ajuda'
    | '/app/condominios'
    | '/app/admin/usuarios/$userId'
    | '/app/ajuda/perfil/$perfil'
    | '/app/admin/usuarios'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/historia'
    | '/login'
    | '/manifesto'
    | '/privacidade'
    | '/signup'
    | '/termos'
    | '/_authenticated/onboarding'
    | '/api/chat'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/app/admin'
    | '/_authenticated/app/ajuda'
    | '/_authenticated/app/conta'
    | '/api/public/demo-chat'
    | '/_authenticated/app/'
    | '/_authenticated/app/admin/auditoria'
    | '/_authenticated/app/admin/blog'
    | '/_authenticated/app/admin/condominios'
    | '/_authenticated/app/admin/financeiro'
    | '/_authenticated/app/admin/orientacoes'
    | '/_authenticated/app/admin/treinamento'
    | '/_authenticated/app/admin/uso'
    | '/_authenticated/app/ajuda/$secao'
    | '/_authenticated/app/ajuda/dicas-ia'
    | '/_authenticated/app/ajuda/faq'
    | '/_authenticated/app/condominios/$id'
    | '/_authenticated/app/admin/'
    | '/_authenticated/app/ajuda/'
    | '/_authenticated/app/condominios/'
    | '/_authenticated/app/admin/usuarios/$userId'
    | '/_authenticated/app/ajuda/perfil/$perfil'
    | '/_authenticated/app/admin/usuarios/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HistoriaRoute: typeof HistoriaRoute
  LoginRoute: typeof LoginRoute
  ManifestoRoute: typeof ManifestoRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  SignupRoute: typeof SignupRoute
  TermosRoute: typeof TermosRoute
  ApiChatRoute: typeof ApiChatRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiPublicDemoChatRoute: typeof ApiPublicDemoChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifesto': {
      id: '/manifesto'
      path: '/manifesto'
      fullPath: '/manifesto'
      preLoaderRoute: typeof ManifestoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/demo-chat': {
      id: '/api/public/demo-chat'
      path: '/api/public/demo-chat'
      fullPath: '/api/public/demo-chat'
      preLoaderRoute: typeof ApiPublicDemoChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/conta': {
      id: '/_authenticated/app/conta'
      path: '/app/conta'
      fullPath: '/app/conta'
      preLoaderRoute: typeof AuthenticatedAppContaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ajuda': {
      id: '/_authenticated/app/ajuda'
      path: '/app/ajuda'
      fullPath: '/app/ajuda'
      preLoaderRoute: typeof AuthenticatedAppAjudaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/admin': {
      id: '/_authenticated/app/admin'
      path: '/app/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AuthenticatedAppAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/condominios/': {
      id: '/_authenticated/app/condominios/'
      path: '/app/condominios'
      fullPath: '/app/condominios/'
      preLoaderRoute: typeof AuthenticatedAppCondominiosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ajuda/': {
      id: '/_authenticated/app/ajuda/'
      path: '/'
      fullPath: '/app/ajuda/'
      preLoaderRoute: typeof AuthenticatedAppAjudaIndexRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/admin/': {
      id: '/_authenticated/app/admin/'
      path: '/'
      fullPath: '/app/admin/'
      preLoaderRoute: typeof AuthenticatedAppAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/condominios/$id': {
      id: '/_authenticated/app/condominios/$id'
      path: '/app/condominios/$id'
      fullPath: '/app/condominios/$id'
      preLoaderRoute: typeof AuthenticatedAppCondominiosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/ajuda/faq': {
      id: '/_authenticated/app/ajuda/faq'
      path: '/faq'
      fullPath: '/app/ajuda/faq'
      preLoaderRoute: typeof AuthenticatedAppAjudaFaqRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/ajuda/dicas-ia': {
      id: '/_authenticated/app/ajuda/dicas-ia'
      path: '/dicas-ia'
      fullPath: '/app/ajuda/dicas-ia'
      preLoaderRoute: typeof AuthenticatedAppAjudaDicasIaRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/ajuda/$secao': {
      id: '/_authenticated/app/ajuda/$secao'
      path: '/$secao'
      fullPath: '/app/ajuda/$secao'
      preLoaderRoute: typeof AuthenticatedAppAjudaSecaoRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/admin/uso': {
      id: '/_authenticated/app/admin/uso'
      path: '/uso'
      fullPath: '/app/admin/uso'
      preLoaderRoute: typeof AuthenticatedAppAdminUsoRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/treinamento': {
      id: '/_authenticated/app/admin/treinamento'
      path: '/treinamento'
      fullPath: '/app/admin/treinamento'
      preLoaderRoute: typeof AuthenticatedAppAdminTreinamentoRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/orientacoes': {
      id: '/_authenticated/app/admin/orientacoes'
      path: '/orientacoes'
      fullPath: '/app/admin/orientacoes'
      preLoaderRoute: typeof AuthenticatedAppAdminOrientacoesRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/financeiro': {
      id: '/_authenticated/app/admin/financeiro'
      path: '/financeiro'
      fullPath: '/app/admin/financeiro'
      preLoaderRoute: typeof AuthenticatedAppAdminFinanceiroRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/condominios': {
      id: '/_authenticated/app/admin/condominios'
      path: '/condominios'
      fullPath: '/app/admin/condominios'
      preLoaderRoute: typeof AuthenticatedAppAdminCondominiosRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/blog': {
      id: '/_authenticated/app/admin/blog'
      path: '/blog'
      fullPath: '/app/admin/blog'
      preLoaderRoute: typeof AuthenticatedAppAdminBlogRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/auditoria': {
      id: '/_authenticated/app/admin/auditoria'
      path: '/auditoria'
      fullPath: '/app/admin/auditoria'
      preLoaderRoute: typeof AuthenticatedAppAdminAuditoriaRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/admin/usuarios/': {
      id: '/_authenticated/app/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/app/admin/usuarios/'
      preLoaderRoute: typeof AuthenticatedAppAdminUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
    '/_authenticated/app/ajuda/perfil/$perfil': {
      id: '/_authenticated/app/ajuda/perfil/$perfil'
      path: '/perfil/$perfil'
      fullPath: '/app/ajuda/perfil/$perfil'
      preLoaderRoute: typeof AuthenticatedAppAjudaPerfilPerfilRouteImport
      parentRoute: typeof AuthenticatedAppAjudaRoute
    }
    '/_authenticated/app/admin/usuarios/$userId': {
      id: '/_authenticated/app/admin/usuarios/$userId'
      path: '/usuarios/$userId'
      fullPath: '/app/admin/usuarios/$userId'
      preLoaderRoute: typeof AuthenticatedAppAdminUsuariosUserIdRouteImport
      parentRoute: typeof AuthenticatedAppAdminRoute
    }
  }
}

interface AuthenticatedAppAdminRouteChildren {
  AuthenticatedAppAdminAuditoriaRoute: typeof AuthenticatedAppAdminAuditoriaRoute
  AuthenticatedAppAdminBlogRoute: typeof AuthenticatedAppAdminBlogRoute
  AuthenticatedAppAdminCondominiosRoute: typeof AuthenticatedAppAdminCondominiosRoute
  AuthenticatedAppAdminFinanceiroRoute: typeof AuthenticatedAppAdminFinanceiroRoute
  AuthenticatedAppAdminOrientacoesRoute: typeof AuthenticatedAppAdminOrientacoesRoute
  AuthenticatedAppAdminTreinamentoRoute: typeof AuthenticatedAppAdminTreinamentoRoute
  AuthenticatedAppAdminUsoRoute: typeof AuthenticatedAppAdminUsoRoute
  AuthenticatedAppAdminIndexRoute: typeof AuthenticatedAppAdminIndexRoute
  AuthenticatedAppAdminUsuariosUserIdRoute: typeof AuthenticatedAppAdminUsuariosUserIdRoute
  AuthenticatedAppAdminUsuariosIndexRoute: typeof AuthenticatedAppAdminUsuariosIndexRoute
}

const AuthenticatedAppAdminRouteChildren: AuthenticatedAppAdminRouteChildren = {
  AuthenticatedAppAdminAuditoriaRoute: AuthenticatedAppAdminAuditoriaRoute,
  AuthenticatedAppAdminBlogRoute: AuthenticatedAppAdminBlogRoute,
  AuthenticatedAppAdminCondominiosRoute: AuthenticatedAppAdminCondominiosRoute,
  AuthenticatedAppAdminFinanceiroRoute: AuthenticatedAppAdminFinanceiroRoute,
  AuthenticatedAppAdminOrientacoesRoute: AuthenticatedAppAdminOrientacoesRoute,
  AuthenticatedAppAdminTreinamentoRoute: AuthenticatedAppAdminTreinamentoRoute,
  AuthenticatedAppAdminUsoRoute: AuthenticatedAppAdminUsoRoute,
  AuthenticatedAppAdminIndexRoute: AuthenticatedAppAdminIndexRoute,
  AuthenticatedAppAdminUsuariosUserIdRoute:
    AuthenticatedAppAdminUsuariosUserIdRoute,
  AuthenticatedAppAdminUsuariosIndexRoute:
    AuthenticatedAppAdminUsuariosIndexRoute,
}

const AuthenticatedAppAdminRouteWithChildren =
  AuthenticatedAppAdminRoute._addFileChildren(
    AuthenticatedAppAdminRouteChildren,
  )

interface AuthenticatedAppAjudaRouteChildren {
  AuthenticatedAppAjudaSecaoRoute: typeof AuthenticatedAppAjudaSecaoRoute
  AuthenticatedAppAjudaDicasIaRoute: typeof AuthenticatedAppAjudaDicasIaRoute
  AuthenticatedAppAjudaFaqRoute: typeof AuthenticatedAppAjudaFaqRoute
  AuthenticatedAppAjudaIndexRoute: typeof AuthenticatedAppAjudaIndexRoute
  AuthenticatedAppAjudaPerfilPerfilRoute: typeof AuthenticatedAppAjudaPerfilPerfilRoute
}

const AuthenticatedAppAjudaRouteChildren: AuthenticatedAppAjudaRouteChildren = {
  AuthenticatedAppAjudaSecaoRoute: AuthenticatedAppAjudaSecaoRoute,
  AuthenticatedAppAjudaDicasIaRoute: AuthenticatedAppAjudaDicasIaRoute,
  AuthenticatedAppAjudaFaqRoute: AuthenticatedAppAjudaFaqRoute,
  AuthenticatedAppAjudaIndexRoute: AuthenticatedAppAjudaIndexRoute,
  AuthenticatedAppAjudaPerfilPerfilRoute:
    AuthenticatedAppAjudaPerfilPerfilRoute,
}

const AuthenticatedAppAjudaRouteWithChildren =
  AuthenticatedAppAjudaRoute._addFileChildren(
    AuthenticatedAppAjudaRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAppAdminRoute: typeof AuthenticatedAppAdminRouteWithChildren
  AuthenticatedAppAjudaRoute: typeof AuthenticatedAppAjudaRouteWithChildren
  AuthenticatedAppContaRoute: typeof AuthenticatedAppContaRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCondominiosIdRoute: typeof AuthenticatedAppCondominiosIdRoute
  AuthenticatedAppCondominiosIndexRoute: typeof AuthenticatedAppCondominiosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAppAdminRoute: AuthenticatedAppAdminRouteWithChildren,
  AuthenticatedAppAjudaRoute: AuthenticatedAppAjudaRouteWithChildren,
  AuthenticatedAppContaRoute: AuthenticatedAppContaRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCondominiosIdRoute: AuthenticatedAppCondominiosIdRoute,
  AuthenticatedAppCondominiosIndexRoute: AuthenticatedAppCondominiosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HistoriaRoute: HistoriaRoute,
  LoginRoute: LoginRoute,
  ManifestoRoute: ManifestoRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  SignupRoute: SignupRoute,
  TermosRoute: TermosRoute,
  ApiChatRoute: ApiChatRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiPublicDemoChatRoute: ApiPublicDemoChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
